<?php
/**
* Implements hook_preprocess_HOOK() for block.html.twig.
*/
function yearbook_preprocess_block(&$variables) {
// Logos block.
	if ($variables['plugin_id'] === "block_content:483dbe2b-529a-467c-a6a5-773c30b18fc3") {
	  $variables['attributes']['class'][] = 'logos';
	}
// Site title (branding) block.
	if ($variables['plugin_id'] === "block_content:483dbe2b-529a-467c-a6a5-773c30b18fc3") {
	  $variables['attributes']['class'][] = 'site-title';
	}
}